### ISSUE TITLE
Code release and some typos in the paper

### ISSUE THREAD

**Issue by JosephPai** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#1]
Hi authors,

Thanks for the amazing work!
I really like this paper.
I'd like to know when do you plan to open source the code and checkpoint?

There are some typos in this paper. (Will update if I found more)
1. line 3 of Fig 3 caption: "object".
2. First paragraph of Section 3. The red mark of the three types of prompts are not consistent. Also, they are not reflected in Eq. (3), but in Eq. (1).

**Comment by aniki-ly** [comment]
Excellent job! I am also eagerly anticipating the code.

**Comment by HaoZhang534** [comment]
@JosephPai Thank you for your good advice! We will revise the paper in the next version. Our code will be released later in this repo.

**Comment by sauhaardac** [comment]
@HaoZhang534 any approximate timeline for code release? Waiting eagerly for it! Great work.
