### ISSUE TITLE
TypeError: object of type 'AspectRatioGroupedDataset' has no len()

### ISSUE THREAD

**Issue by EricZavier** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#102]
Thanks for your great works

I encountered the following issues during pre training

/pipeline/XDecoderPipeline.py"
 self.train_dataloaders = self.pipeline.get_dataloaders(self, 'train', is_evaluation=False)
  File "/home/wkx/SEEM/./pipeline/XDecoderPipeline.py", line 73, in get_dataloaders
    logger.info(f'num of train samples: {len(dataloader)}')
TypeError: object of type 'AspectRatioGroupedDataset' has no len()
![2023-12-05 09-29-44 的屏幕截图](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/151508880/81ecf34c-fff6-4f6c-94c0-a9b9523d0222)
i dont know why the object of type 'AspectRatioGroupedDataset' has no len()

**Comment by MaureenZOU** [comment]
Please use the customized detectron2.git+https://github.com/MaureenZOU/detectron2-xyz.git

**Comment by EricZavier** [comment]
Thank you so much for your prompt and accurate response.
