### ISSUE TITLE
Demo link is not working / seems broken

### ISSUE THREAD

**Issue by EyGy** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#106]
Hi there and thanks for your amazing work!
I just wanted to let you know that the demo link seems to be broken.
I also tried the huggingface demo, which also didn't work.

Am I alone with this issue?

Thanks in adavance!

**Comment by MaureenZOU** [comment]
Thanks so much! I will fix shortly

**Comment by zsy7532** [comment]
> Thanks so much! I will fix shortly

Hello, the demo link still does not work, could you fix it? Thanks.

**Comment by MaureenZOU** [comment]
Thanks for the reminder, it is fixed last week : )
