### ISSUE TITLE
Semantic segmentation GT file

### ISSUE THREAD

**Issue by msdkarimi** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#118]
Can you kindly tell me where can I find sem_seg GT file? 
I have problem in validation of see_seg, the main problem is about the category of each pixel in grayscale.
Thanks in advance.

**Comment by MaureenZOU** [comment]
For semantic segmentation ground truth file, please refer to mask2former, https://github.com/facebookresearch/Mask2Former
