### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by PrieureDeSion** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#12]
Thanks for the great work! The demo is very inspiring and we are excited about it's potential applications in downstream tasks, especially in robotics. Do you have an ETA on when the code would be released?

We would love to play with the thresholds (seems to have many false positives in the demo) to see if this is useful out of the box. Please let me know! Happy to reach out privately as well.

Thanks
Dhruv (UC Berkeley)

**Comment by MaureenZOU** [comment]
Thanks so much for your interests in our work, we plan to at least release the inference code and tiny model on mid or late may. We will try our best to release training pipeline and large model asap.

**Comment by MaureenZOU** [comment]
Also personally I am very interested in integrating SEEM with robotics applications.

**Comment by unriddler** [comment]
> Thanks so much for your interests in our work, we plan to at least release the inference code and tiny model on mid or late may. We will try our best to release training pipeline and large model asap.

Hi buddy,
Will we release the training code?
