### ISSUE TITLE
Local inference for an image given point prompt coordinates

### ISSUE THREAD

**Issue by JayParanjape** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#128]
Hi, Thank you for the amazing work
I want to run SEEM on a single image locally. I want to segment out an object of interest given a point prompt from the image. Please guide on what script to run and what changes to make for that

**Comment by bratjay01** [comment]
I'm afraid there's no test script available yet for SEEM. #104 
I've been trying to do a similar test, to segment a particular region with bounding box and text prompts. The demo files and xdecoder scripts are a bit helpful to make a test script , even though I've not been able to get it to work yet :)

**Comment by MaureenZOU** [comment]
We do not support inference code currently. @bratjay01 mentioned please refer to those documents.
