### ISSUE TITLE
Results on open-vocabulary panoptic segmentation

### ISSUE THREAD

**Issue by segments-tobias** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#13]
In your paper, you mention

>  "...strong performance on many segmentation tasks including closed-set and open-set
panoptic segmentation, ...

I cannot seem to find the section on **open-set panoptic segmentation**. Do you have results on this task?

**Comment by MaureenZOU** [comment]
Currently, we do not provide open vocabulary panoptic evaluation on SEEM, but will consider providing number in our next version.  If you would like to try open-set panoptic segmentation, please refer to X-Decoder https://huggingface.co/spaces/xdecoder/Demo
