### ISSUE TITLE
Bug when getting the neg_mask

### ISSUE THREAD

**Issue by Lewislou** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#132]
![image](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/23080469/f27ff835-f3f4-4b80-9957-9a85b2aeec43)
I assum that "x['spatial_query']['rand_shape'].to(self.device) & False)"  is to get the reverse map of the input masks. So when the area of the mask is True, it should reture False, otherwise, it return True. So that the neg_mask is representing the background area. But "False & False" is stilling False. Would this a bug? I guess we should use "==" here.

**Comment by MaureenZOU** [comment]
For & False, it will return all the neg_masks initialized with a blank mask. And the updating of neg_masks is happening at https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/7b2e76dbb17d0b7831c6813a921fe2bc8de22926/modeling/architectures/seem_model_v0.py#L958
