### ISSUE TITLE
Ask about using SEEM with SA3D

### ISSUE THREAD

**Issue by mw-JHC** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#142]
Hello everyone.

First of all, thank you so much for sharing your results!
It is so interesting for me.

I want to create a dataset labeled with a 3D reconstruction, and because of this reconstruction, I have a question about using SEEM with SA3D.

1. To use SEEM with SA3D, do I need to have a reference video created by SA3D or is it okay to have a 3D reconstruction video created by NeRF or even a normal video?
2. How can I get annotation data (coco) for a video from your demo GUI? (when i download it... it don't work.)
3. In the case of the input brushes used in your demo, are there multiple pixels being input?

Thanks in advance for any answers.

**Comment by MaureenZOU** [comment]
1. I believe a 3D reconstruction video or a normal video is fine.
2. We are not currently supporting downloading the COCO annotation format. But this would be a great suggestion, feel free to create a push request, or I will also consider supporting this.
3. It supports multiple pixels. If you want a multiple object support demo, feel free to use SOM demo with the smallest granularity: https://som-gpt4v.github.io/
