### ISSUE TITLE
inference demo of ref_img setting

### ISSUE THREAD

**Issue by XiaokunFeng** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#143]
Thanks for your great work!!!

I noticed that you have thoughtfully provided some inference demos in the 'inference/xdecoder' directory. Could you please provide an inference demo based on the 'reference image + text' prompt combination? 
Alternatively, could you help explain the data dimensions and meanings of img and mask under the refimg setting? Thank you.

**Comment by MaureenZOU** [comment]
If you want to play with the reference image + text prompt combination, please go ahead to play with the SEEM demo https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/7b2e76dbb17d0b7831c6813a921fe2bc8de22926/demo/seem/tasks/interactive.py#L35, it supports integration of arbitrary input prompts.

**Comment by XiaokunFeng** [comment]
Thank you for your response. I also noticed this infer function. In this function, the input image and refimg are dictionaries that contain two keys: "image" and "mask". What confuses me is the data format of the mask. Could you please explain this based on the following example?

Suppose I want to perform a video object segmentation task, and the length and width of the test video frames are 224, while the length and width of the reference image are 112 (the entire image is used as a prompt). In this case, how should the "mask" for both image and refimg be set? Thank you.
![image](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/103614531/64729f96-e5f4-42a2-ac06-27f487a88476)
