### ISSUE TITLE
ModuleNotFoundError: No module named 'modeling'

### ISSUE THREAD

**Issue by Note-Liu** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#146]
root@lx:/code/Segment-Everything-Everywhere-All-At-Once-1.0# python3.8 demo/seem/app.py 
Traceback (most recent call last):
  File "demo/seem/app.py", line 21, in <module>
    from modeling.BaseModel import BaseModel
ModuleNotFoundError: No module named 'modeling'

root@lx:/code/Segment-Everything-Everywhere-All-At-Once-1.0# python3.8
Python 3.8.0 (default, Jun 22 2021, 16:50:47) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from modeling.BaseModel import BaseModel
/usr/local/lib/python3.8/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/usr/local/lib/python3.8/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/usr/local/lib/python3.8/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Deformable Transformer Encoder is not available.

I encountered this problem after executing 
git clone git@github.com:UX-Decoder/Segment-Everything-Everywhere-All-At-Once.git && sh assets/scripts/run_demo.sh
How can I solve it?

**Comment by XunG28** [comment]
请问下 这个问题怎么解决的？遇到一样的问题了

**Comment by Note-Liu** [comment]
> 请问下 这个问题怎么解决的？遇到一样的问题了

Use the following command to install the encoder first:
cd modeling/vision/encoder/ops && sh make.sh && cd ../../../../
