### ISSUE TITLE
If there are multiple objects in the image, why is only one selected?

### ISSUE THREAD

**Issue by Note-Liu** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#147]
![Screenshot from 2024-06-17 11-18-14](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/45785807/8d581d2e-09e5-4b03-acca-7e87e379911a)

**Comment by dyaxoio** [comment]
Did you figure it out?
