### ISSUE TITLE
502 Bad Gateway?

### ISSUE THREAD

**Issue by XiaolanPan** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#15]
Hello, I just wanted to access the demo of the video, and there was an error in the title. Is there something wrong?https://36d0f3ae0b147b22.gradio.app

**Comment by MaureenZOU** [comment]
Thanks a lot for raising this issue, I am rebooting and merge to hugging face.

**Comment by MaureenZOU** [comment]
https://083193edbb48f717.gradio.app try here.
