### ISSUE TITLE
Panoptic segmentation failing

### ISSUE THREAD

**Issue by juansebashr** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#17]
In the SEEM [huggingface space](https://huggingface.co/spaces/xdecoder/SEEM) selecting the panoptic segmentation with just the image is not working, with every image I'm getting an error on the output, could anyone help me with that?

**Comment by MaureenZOU** [comment]
Thanks for raising this issue, I have fixed the bug and rebuild hugging face demo. 

That is caused by the return variable does not change for panoptic segmentation while I add video segmentation with two output panel.
