### ISSUE TITLE
Visual referring data process

### ISSUE THREAD

**Issue by ltm920716** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#18]
hi,
    Thank you for your work! 
    I am very interested in the part of Visual referring.  There is little information about the data processing for training in the paper, so could you please share some key points of visual referring data processing for training? Thanks!

**Comment by MaureenZOU** [comment]
Thanks so much for your interest. We actually do not specifically trained with visual referring, that is a "zero-shot" effect of our visual sampler.

**Comment by ltm920716** [comment]
thanks！
