### ISSUE TITLE
Demo code installation

### ISSUE THREAD

**Issue by AntonioGonzalezSuarez** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#21]
**Using windows WSL and trying to run the demo code.**

I get an error while installing the requirements. For some reason it starts with the github repositories linked in the requirements.txt.

While installing from [https://github.com/MaureenZOU/detectron2-xyz.git](url) you get an error saying ModuleNotFoundError: No module named 'torch'.

By installing manually the torch module the error is solved but I don´t think this is ideal.

Another issue comes from the run_demo.sh, at least in my case it is not recognizing the sudo apt commands making it fail. Again if I do the commands manually it works.

**Comment by AntonioGonzalezSuarez** [comment]
Sudo happens only in my computer for some reason but the requirements problem can be replicated.

**Comment by MaureenZOU** [comment]
Thanks a lot that would be a very great suggestions, would provide detailed instructors for Windows and Mac Users.

**Comment by tharkhay** [comment]
#24

**Comment by GoGoPen** [comment]
Delete the following last three lines from the requirements.txt
```
'git+https://github.com/arogozhnikov/einops.git'
'git+https://github.com/MaureenZOU/detectron2-xyz.git'
'git+https://github.com/openai/whisper.git'
```


And add the following line in run_demo.sh after 
pip install -r requiremenmts.txt
```
pip install 'git+https://github.com/arogozhnikov/einops.git'
pip install 'git+https://github.com/MaureenZOU/detectron2-xyz.git'
pip install 'git+https://github.com/openai/whisper.git'
```
Note, you may use python 3.9.
