### ISSUE TITLE
Questions about water surfaces and mirrors

### ISSUE THREAD

**Issue by ICE-Bro** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#23]
Thanks for your great work! I noticed that your demo can identify water surfaces and mirrors well without misclassifying them due to reflections. Is there any specific design for this?

**Comment by MaureenZOU** [comment]
Interesting, I am surprised about this too! Could you please share the demo image? As what I am asking, we do not have any specific design : )

**Comment by ICE-Bro** [comment]
![u=61183202,3425279497 fm=253 app=138 size=w931 n=0 f=JPEG fmt=auto](https://user-images.githubusercontent.com/61672532/235275081-44b46851-4a8f-4510-90b3-9fcc59fc7e10.png)
![下载](https://user-images.githubusercontent.com/61672532/235275213-db5107cd-a880-4aa1-905e-803c401fd4a4.png)
The second picture is the prediction of the demo.

**Comment by ICE-Bro** [comment]
![u=1485483307,3899651903 fm=253 fmt=auto app=138 f=JPEG](https://user-images.githubusercontent.com/61672532/235276816-5818f035-53ce-49db-9c20-5dd9f00506db.png)
![下载 (1)](https://user-images.githubusercontent.com/61672532/235276823-4510f67a-8909-4519-acb7-5727631a62de.png)

**Comment by MaureenZOU** [comment]
I see, thanks for submitting the image! This is actually caused by these two categories are actually in coco training dataset, not because of zero-shot generalization.
