### ISSUE TITLE
Checkpoint for Gradio Demo

### ISSUE THREAD

**Issue by ldkong1205** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#24]
Thanks for open-sourcing your great work!

I have tried your Gradio demo and it works very well. I wonder whether your released checkpoint, i.e., 'seem_focalt_v1.pt`, is the same one that was used in the demo. Thanks!

**Comment by pablopalafox** [comment]
Hi @MaureenZOU! Is there any chance that you guys will release the large model as well? :)

**Comment by ldkong1205** [comment]
Same question. Is there an estimated time for the release of your larger models? Thanks!

**Comment by msk7131** [comment]
Same question. Is there an estimated time for the release of your larger models? Thanks!

**Comment by MaureenZOU** [comment]
I am running a large model with publishable checkpoint. But expected to be slightly worse than the demo checkpoint.

**Comment by ldkong1205** [comment]
> I am running a large model with publishable checkpoint. But expected to be slightly worse than the demo checkpoint.

Thanks for your information! Is this model performing better than the released tiny model?

**Comment by MaureenZOU** [comment]
That would be better than focalt checkpoint. It is trained with in21k pretrained focall-x-decoder.

**Comment by ldkong1205** [comment]
> That would be better than focalt checkpoint. It is trained with in21k pretrained focal-large.

Great! Could you please release this one first? Thanks a lot for your help!

**Comment by MaureenZOU** [comment]
As may may noticed, this one is still traning.

**Comment by ldkong1205** [comment]
> As you may noticed, this one is still training. Expected 1-2 days to be finished without interrupt.

Thanks for letting me know. Looking forward to it!

**Comment by MaureenZOU** [comment]
We have released the focal-large checkpoint and config, feel free to play with it.

**Comment by ldkong1205** [comment]
> We have released the focal-large checkpoint and config, feel free to play with it.

Thanks a lot for your prompt help!
