### ISSUE TITLE
Video demo with Referring Text

### ISSUE THREAD

**Issue by xiaofan-luan** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#27]
As far as my current understanding. Video demos only support draw on referring image.
Is there any limitation on it? can we use text or audio prompt?

**Comment by MaureenZOU** [comment]
Our video version is also able to support text and audio. But if you would like to use the text prompt for video please checkout X-Decoder that has better performance: https://github.com/microsoft/X-Decoder, and please refer to the video demo: https://youtu.be/nZZTkYM0kd0?t=27
