### ISSUE TITLE
Finetuning code (training code)

### ISSUE THREAD

**Issue by pablopalafox** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#28]
Hey folks! Super cool stuff. Looking forward to seeing some code for finetuning! :)

**Comment by AllenDun** [comment]
+1

**Comment by wojiaohumaocheng** [comment]
+1

**Comment by vitality-zyx** [comment]
@MaureenZOU

**Comment by jwyang** [comment]
Thanks for your interest! We will release the code next month. Stay tunned!

**Comment by MaureenZOU** [comment]
We just released a comprehensive training code for both SEEM and X-Decoder at https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once, feel free to play with it and raise any issue. I will continuously support the code base!
