### ISSUE TITLE
Awesome! Does it segment with text in e2e mode?

### ISSUE THREAD

**Issue by jinfagang** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#3]
Does it need detection first and then using box to segmentation like SAM?

**Comment by MaureenZOU** [comment]
Hi,

Thanks for your question. We are not doing in that way, our model is clean and very simple as shown in the below figure, mask output and class output will directly computed by Mask and Class embeddings with similarity regard to image and language feature.

<img width="886" alt="Screenshot 2023-04-14 at 3 48 07 AM" src="https://user-images.githubusercontent.com/11957155/231993799-35b54499-7523-4d79-bc60-7891de3b528e.png">

**Comment by jinfagang** [comment]
@MaureenZOU how many maxium class the mask can predicts? (when not using text prompt)

**Comment by MaureenZOU** [comment]
Maximum is unlimited, but the performance would be decreased.

**Comment by jinfagang** [comment]
@MaureenZOU does it combines coco or other open datasets togather?

**Comment by MaureenZOU** [comment]
Now we only use coco 133 classes.
