### ISSUE TITLE
Help: how to extract feature given a mask/region of an image?

### ISSUE THREAD

**Issue by nessessence** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#31]
Hi, I'm wondering how to extract feature given a ground truth mask/region of an image using SEEM.

Thanks

**Comment by MaureenZOU** [comment]
Actually for semantic representation, consider using class embedding : )
https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/489a6c2f2146377b3903619f98f06f52ac60bbc6/demo_code/xdecoder/body/decoder/seem.py#L558
