### ISSUE TITLE
When interactivate mode is stroke, RuntimeError: "upsample_bilinear2d_channels_last" not implemented for 'Byte'

### ISSUE THREAD

**Issue by zzl-997** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#34]
When interactivate mode is stroke, RuntimeError: "upsample_bilinear2d_channels_last" not implemented for 'Byte'
The error may locate in "demo_code/tasks/interactive.py  mask_ori = (F.interpolate(mask_ori, (height, width), mode='bilinear', align_corners=True) > 0)"
return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)

**Comment by 5663015** [comment]
I have the same error.

**Comment by MaureenZOU** [comment]
Please upgrade pytorch2.0

**Comment by AlexJunCpp** [comment]
I have the same error

**Comment by zzl-997** [comment]
For each "F.interpolate(..." in demo_code/tasks/interactive.py, make modification as follows:

ori_dtype = refimg_mask.dtype
refimg_mask = torch.tensor(refimg_mask, dtype=torch.float32)
refimg_mask = (F.interpolate(refimg_mask, (_height, _width), mode='bilinear', align_corners=True) > 0)
refimg_mask = torch.tensor(refimg_mask, dtype=ori_dtype)
and then this issue will fixed.

The reason may be that the refimg_mask.dtype is torch.uint8
![image](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/63634296/833e6ad3-644c-4414-b82b-edfdfd1c6c08)

**Comment by MaureenZOU** [comment]
Right, <pytorch2.0 does not support bool interpolation.
