### ISSUE TITLE
Why does it just show one object in the pic ？although the result seems right using "Panoptic"

### ISSUE THREAD

**Issue by AlexJunCpp** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#39]
Why does it just show one object in the pic ？although the result seems right using "Panoptic".   If there is any other setting needed to be changed, please tell me, thx!
![1](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/29520777/06ee85a2-dcf8-438e-98f4-d2c1d521ed3c)
![2](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/29520777/e9e942a0-8fa5-43bd-95f8-f0425172efba)

**Comment by MaureenZOU** [comment]
Sorry, I am not quite understand the question, could you please provide an example to your argument? Thanks!

**Comment by woctezuma** [comment]
I believe the question was about the second person not being detected when using "text", but being detected when using "panoptic".
