### ISSUE TITLE
How to train our custom datasets? 

### ISSUE THREAD

**Issue by leichaoyang** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#41]

**Comment by ddddkk** [comment]
How to train our custom datasets?

**Comment by MaureenZOU** [comment]
We just release a comprehensive training code for both SEEM and X-Decoder at https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once, feel free to play with it and raise any issue. I will continuously support the code base! 

For adding custom datasets please refer to: https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/v1.0/assets/readmes/INSTALL.md
