### ISSUE TITLE
Can it use bounding box prompt to get the label and mask?

### ISSUE THREAD

**Issue by RyanCV** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#42]
Can it use bounding box prompt to get the label and mask?

**Comment by MaureenZOU** [comment]
Yes, it could do this. For bounding box inference, what we are doing is actually we sample the center point and box and use it a s point.

**Comment by RyanCV** [comment]
> 

Could you please provide some demo script for this? I have run the sh run_demo.sh, but there is no options for me to select: e.g., bounding box, text,

**Comment by wenlongli10** [comment]
> Yes, it could do this. For bounding box inference, what we are doing is actually we sample the center point and box and use it a s point.

Can you tell us specifically how to do it? How many points in the final input? Only a central point?
