### ISSUE TITLE
can't download the released model

### ISSUE THREAD

**Issue by miyajiyuta** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#44]
I couldn't download the released mode.
How can I get them?

[SEEM Focal-L](https://projects4jw.blob.core.windows.net/x-decoder/release/seem_focall_v1.pt) and [X-Decoder Focal-L](https://projects4jw.blob.core.windows.net/x-decoder/release/xdecoder_focall_last.pt) checkpoints.

bellow is error message.
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:5c2d36f8-601e-0012-2ca8-93d64b000000 Time:2023-05-31T10:11:10.4213753Z</Message>
</Error>
```

**Comment by danieltudosiu** [comment]
This happens to me too. when I try to wget them.

**Comment by jwyang** [comment]
Thanks for raising the issue. We had updated the links.

**Comment by OliviaMarkham** [comment]
> Thanks for raising the issue. We had updated the links.

I also still get the same error. What was updated?
