### ISSUE TITLE
File Not Found: seem_focall_v1.pt

### ISSUE THREAD

**Issue by OliviaMarkham** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#47]
When I try to run app.py I get this error: 
FileNotFoundError: [Errno 2] No such file or directory: 'seem_focall_v1.pt'

The link(https://projects4jw.blob.core.windows.net/x-decoder/release/seem_focall_v1.pt) seems to go to this page: 
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:b7249e77-701e-0067-6579-968f11000000 Time:2023-06-04T00:17:46.1304179Z</Message>
</Error>

Any assistance would be appreciated.

**Comment by jwyang** [comment]
The error is because the original links are broken, fixed with new huggingface model link.
