### ISSUE TITLE
Always segments person when using text

### ISSUE THREAD

**Issue by joshmyersdean** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#5]
Hello!

Thank you for releasing this great work! I'm trying out the demo on some fashion images and I primarily get the entire person in the segmentation when using text. I have provided some examples below. Thank you!

![image](https://user-images.githubusercontent.com/42389546/232136335-e825472b-ed45-4b3c-bdcf-046126595d24.png)

![image](https://user-images.githubusercontent.com/42389546/232136494-09839552-050b-4dde-8bec-6eeb4783c4be.png)

**Comment by jwyang** [comment]
Hi, @joshmyersdean, thanks for your great interest in our work! Unfortunately, our current SEEM model does not support language-based part segmentation for humans due to the limitation of COCO data we used for training. We are working towards that. Stay tunned!
