### ISSUE TITLE
Question about training with non-prompt, visual-prompt, and text-prompt

### ISSUE THREAD

**Issue by GiantAcidLemon** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#51]
Thanks for sharing the cool results! I have one more detailed question. 
When you train no-prompt, text-prompt, and visual prompts, how do you train them all together? 
Does it mean while training, for every batch, you randomly pick 1 task from 3 tasks (no-prompt, visual prompt, text-prompt)? 
It is not clear how you can train them together when the given prompt not aligned with each other, for example, given text-prompt (e.g., caption of the whole image describing all the objects, say 10) but the visual-prompt only has 1 or 2 points represent 1 or 2 objects. 

Thank you!

**Comment by MaureenZOU** [comment]
We just release a comprehensive training code for both SEEM and X-Decoder at https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once, feel free to play with it and raise any issue. I will continuously support the code base!
