### ISSUE TITLE
fine-tine in custom data

### ISSUE THREAD

**Issue by yican-huang** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#54]
Great job. After reading the article, I was very impressed and interested. I'm not sure if authors have any plans to open source fine-tune the code. Looking forward to it!

**Comment by MaureenZOU** [comment]
Will open source training code shortly, and you could refer to x-decoder training code release: https://github.com/microsoft/X-Decoder

**Comment by MaureenZOU** [comment]
We just release the training code for  both SEEM and X-Decoder, feel free to add a custom dataset https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/v1.0/assets/readmes/DATASET.md
