### ISSUE TITLE
how to eval SEEM on the general semantic segmentation

### ISSUE THREAD

**Issue by MaltoseFlower** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#55]
how to eval the SEEM model on the general semantic segmentation task. Such as Pascal VoC, CityScapes and ADE 20k, etc.

**Comment by fremk** [comment]
Well I'd imagine you need to map the classes from the coco panoptic dataset (seem classes) 134 classes to the classes of the designated dataset. Since the training code is not released yet, and unless you write it yourself, this is in my opinion your second best option.

**Comment by MaureenZOU** [comment]
Will release seem training code shortly as the training code has been cleaned out for x-decoder : ) Or you could directly put the seem model in the code base https://github.com/microsoft/X-Decoder.
