### ISSUE TITLE
Gradio demo error

### ISSUE THREAD

**Issue by TSTB-dev** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#56]
I've tried to play the demo, but I've encountered the following error on the browser preview.

![スクリーンショット 2023-07-10 181303](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/107023038/0424be71-e729-44bb-a757-ca07537e893c)

The Chrome developer tool shows the results of this error.

`index.js:170     POST http://127.0.0.1:7860/run/predict 422 (Unprocessable Entity)`

My environment settings

- OS: Ubuntu22.04

**Comment by Yang-Liu1082** [comment]
I ran into the same issue. Update the gradio version (3.36.1) can fix it.
```
pip uninstall gradio==3.31.0
pip install gradio
```

**Comment by TSTB-dev** [comment]
The issue was resolved with the above solution. Thank you!
