### ISSUE TITLE
Hugging face demo not working

### ISSUE THREAD

**Issue by richardliu1111** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#60]
After clicking the link to the hugging face demo and uploading my video, it looks like this:

<img width="1641" alt="截屏2023-07-25 20 00 09" src="https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/110349683/0a2df26c-da5d-4800-b7b4-2e06b41ed418">

**Comment by MaureenZOU** [comment]
Please select video, and upload a referring i
![Screenshot 2023-07-25 at 5 03 50 PM](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/11957155/c37e456c-45df-4d4f-a917-b12a973f70b1)
mage as in example. Please see below:
