### ISSUE TITLE
How to refine the seg result?

### ISSUE THREAD

**Issue by BruceLz** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#66]
For pictures or videos that need to be segmented, how to improve the segmentation results?

**Comment by MaureenZOU** [comment]
We are not supporting demo for the interactive clicking, but we just support the evaluation mode for interactive segmentation please refer to "pascalvoc_val_Point" at https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/aa64358d9ff0211c8fcb4e016a920a180d0cb7ab/configs/seem/focalt_unicl_lang_v1.yaml#L227C50-L227C69

This contains the refinement procedure.
