### ISSUE TITLE
SEEM-Tiny Checkpoint download permissions issue

### ISSUE THREAD

**Issue by jordanhart** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#68]
[SEEM-Tiny Checkpoint](https://projects4jw.blob.core.windows.net/x-decoder/release/seem_focalt_v1.pt) 

Gives this issue 
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:a53368af-301e-009e-5bde-cb895f000000 Time:2023-08-10T22:57:18.4964017Z</Message>
</Error>

**Comment by MaureenZOU** [comment]
Thanks a lot! We just release all the checkpoints at https://huggingface.co/xdecoder/SEEM/tree/main
