### ISSUE TITLE
Use multiple texts to query an image

### ISSUE THREAD

**Issue by Harry-zzh** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#7]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/54358503/232177693-d6523fdf-c444-4917-bb9a-5eea54885aa7.png">

I wonder how to segment zebra and grass simultaneously. And how to get all the segmentation masks of the zebras?

**Comment by MaureenZOU** [comment]
Thanks for your interest, our model supports this function, but currently, the demo version does not support this, will try to add the function later.
