### ISSUE TITLE
Request for Training Code Release Timeline

### ISSUE THREAD

**Issue by zhangnanyue** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#74]
Dear Author,

Firstly, I'd like to commend you on the fantastic work you've done with this project. I've been exploring its capabilities and am eager to see the training code. Is there a timeline for when this might be available? I believe it would greatly enhance the project's utility for many users like myself.

Thank you for your time and consideration.

Best regards.

**Comment by ddddkk** [comment]
+1

**Comment by MaureenZOU** [comment]
I am currently exactly working on this.

**Comment by ddddkk** [comment]
> I am currently exactly working on this.

Thank you very much. I have been studying SEEM networks recently and hope to train the model through my own dataset as soon as possible. Additionally, I would like to know how point prompt is implemented and trained. Thank you very much!

**Comment by MaureenZOU** [comment]
We just release a comprehensive training code for both SEEM and X-Decoder at https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once, feel free to play with it and raise any issue. I will continuously support the code base!
