### ISSUE TITLE
SOTA Model for Text Prompt Segmentation

### ISSUE THREAD

**Issue by xiaobanni** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#77]
I am looking for a state-of-the-art (SOTA) model for text prompt segmentation. Currently, I am aware of two choices: [Grounded-Segment-Anything](https://github.com/IDEA-Research/Grounded-Segment-Anything) and [SEEM](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once). However, both of these models fail to meet my requirements.

Consider the following example: I want the model to segment the lane lines, but the results from the aforementioned methods are as follows (i hope they can segment the lane line in the road):

Grounded-Segment-Anything:
![image](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/33119031/2ddbf764-f8ee-4f93-b90c-d46275e91fb1)

SEEM Model:
![image](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/33119031/664f5223-9774-47d4-b6ca-3cd169f3c414)

Unfortunately, neither of them can solve this problem effectively. I would greatly appreciate any recommendations you may have.

Suggestions for improving the implementation of the request using SEEM are also appreciated.

**Comment by MaureenZOU** [comment]
At least for us, we are not supporting the lane line without finetuning. That kind of part would be better supported by SAM or Semantic-SAM if you are interested.

**Comment by xiaobanni** [comment]
According to my knowledge, SAM and Semantic-SAM do not open their text-prompt ability for public use. That's the reason I started an issue to track the progress of the text-prompt segment model.

**Comment by MaureenZOU** [comment]
I see, I think the semantic capability of SAM is limited. In this case, I think you may try to finetune our model given the training code : )

**Comment by xiaobanni** [comment]
I am a researcher from another field who wants to use the off-the-shelf text-prompt segmentation model for assistance. Therefore, finetuning seems challenging both technically and in terms of computing resources. I am using Grounded-Segment-Anything as a temporary replacement and keeping an eye on the latest achievements in this area.
