### ISSUE TITLE
Failure to find all objects in text prompt mode

### ISSUE THREAD

**Issue by xiaobanni** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#78]
This issue is similar to Issue #39, which was closed despite remaining unsolved. I would like to provide more details here.

Consider the following example: 

In Panoptic Mode, the system can successfully separate all the cars. 
![image](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/33119031/5f57e95e-1d20-4bc5-9f1b-87aa234e9f92)

However, in Text Mode, if we prompt "car", it can only segment one car.
![image](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/33119031/3f896543-d06d-4918-acbe-f0e6fdca9999)

What is the reason for this? My requirement is to identify all the objects in the image. Is it possible to achieve this using SEEM?

I have delved into the code, and it appears that each image does not support multiple optional masks. Is this correct?

**Comment by MaureenZOU** [comment]
Right, in referring mode, we only find the best object that matches the referring text/visual/spatial prompts. It is an open question to support finding all the matched instances.

**Comment by xiaobanni** [comment]
May I ask whether there is a plan to provide all the potential segments for a specific prompt with accuracy values? This seems to be a widely adopted implementation.

**Comment by MaureenZOU** [comment]
I think given the current code, it is able to get the probability like: https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/431e773c6825c0e0ddb54ae42e72489035ed3fa7/demo/seem/tasks/interactive.py#L153

**Comment by xiaobanni** [comment]
I debugged the code and found that `out_prob` only returns the probability of the predefined object class for the most probable segment. Therefore, I can't retrieve all the potential segments by dealing with this line of code.
