### ISSUE TITLE
Training set for the gradio demo

### ISSUE THREAD

**Issue by GiantAcidLemon** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#80]
Hi thanks for sharing this code! What dataset are you using for the gradio demo? Thank you!

**Comment by MaureenZOU** [comment]
The Gradio demo we are using is coco only. You can exactly reproduce with the given config https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/v1.0/configs/seem/focall_unicl_lang_v1.yaml
