### ISSUE TITLE
Multiple Interactive object inference demo example

### ISSUE THREAD

**Issue by jordanhart** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#81]
Hi, could you walk us through how to use the inference of "Supporting Multiple Interactive objects training and inference" with a demo example? Thank you for all the amazing work and support.

**Comment by jordanhart** [comment]
Hey! Just checking back on this @MaureenZOU. Really appreciate all the work and will be ecstatic whenever this is released

**Comment by MaureenZOU** [comment]
I sincerely apologize that I currently do not have time to build a multi-object demo, but SoM use the multi-object interactive mode for SEEM, you can check the code at: https://github.com/microsoft/SoM/blob/main/task_adapter/seem/tasks/inference_seem_interactive.py
