### ISSUE TITLE
Error when running training script

### ISSUE THREAD

**Issue by theodore-zhao** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#83]
I kept getting the following error when running the training code of SAM ViT-B:

`ImportError: /opt/conda/lib/python3.9/site-packages/detectron2/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c106SymInt19promote_to_negativeEv
`
All datasets are readily in place as instructed. I installed the requirements in the docker environment below:

```
FROM wangkenpu/pytorch:1.8.0-py39-cuda11.1-cudnn8-ubuntu18.04

RUN pip install --upgrade pip

RUN pip install -I torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
RUN pip install kornia
RUN pip install timm==0.4.12
RUN python -m pip install 'git+https://github.com/MaureenZOU/detectron2-xyz.git'
RUN pip install git+https://github.com/cocodataset/panopticapi.git
RUN pip install git+https://github.com/openai/CLIP.git

RUN wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth

COPY assets/requirements/requirements.txt /tmp/requirements.txt
RUN python -m pip install -r /tmp/requirements.txt

COPY assets/requirements/requirements_custom.txt /tmp/requirements_custom.txt
RUN python -m pip install -r /tmp/requirements_custom.txt

#RUN pip install -U protobuf

# Set environment variables
ENV MKL_THREADING_LAYER=GNU
ENV NCCL_DEBUG=INFO

```
Do you have any idea what might be wrong?

**Comment by MaureenZOU** [comment]
May I ask what is your cuda version and GPU type? And I am a little bit curious why do you start from this docker "wangkenpu/pytorch:1.8.0-py39-cuda11.1-cudnn8-ubuntu18.04", as this is exactly the docker I was used to train the model, Hhh

**Comment by theodore-zhao** [comment]
> May I ask what is your cuda version and GPU type? And I am a little bit curious why do you start from this docker "wangkenpu/pytorch:1.8.0-py39-cuda11.1-cudnn8-ubuntu18.04", as this is exactly the docker I was used to train the model, Hhh

My CUDA version is 11.1. GPU type is A6000. 
I've been collaborating with members on the team, so this docker image was used to setup the environment for SEESAM previously hhh.

**Comment by MaureenZOU** [comment]
Interesting, your environment should be fine. One potential problem, pip install -I torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113, this will install pytorch 2.1.xx, that docker is not compatible with the latest torch version. Please try this "pip install -I torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --user"

**Comment by theodore-zhao** [comment]
> Interesting, your environment should be fine. One potential problem, pip install -I torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113, this will install pytorch 2.1.xx, that docker is not compatible with the latest torch version. Please try this "pip install -I torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --user"

I changed the Dockerfile to be 

```
FROM wangkenpu/pytorch:1.8.0-py39-cuda11.1-cudnn8-ubuntu18.04

COPY assets/requirements/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY assets/requirements/requirements_custom.txt /tmp/requirements_custom.txt
RUN pip install -r /tmp/requirements_custom.txt
```

And modified the requirements.txt with
`torch==2.0.1 
torchvision==0.15.2 
torchaudio==2.0.2`

It seems working now! Except the following missing dataset:
`FileNotFoundError: [Errno 2] No such file or directory: 'xdecoder_data/coco/annotations/panoptic_train2017_filtrefgumdval.json'`

I guess we need this file as well? The current file I have under the directory is 'xdecoder_data/coco/annotations/panoptic_train2017_filtrefgumdval_filtvlp.json'

**Comment by MaureenZOU** [comment]
For file download please refer to: https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/v1.0/assets/readmes/DATASET.md 
Feel free to create pull request if you meet any problem and get a fix : )

**Comment by theodore-zhao** [comment]
Thanks!

**Comment by Lijiaxin0111** [comment]
It seems working now! Except the following missing dataset:
FileNotFoundError: [Errno 2] No such file or directory: 'xdecoder_data/coco/annotations/panoptic_train2017_filtrefgumdval.json'

I guess we need this file as well? The current file I have under the directory is 'xdecoder_data/coco/annotations/panoptic_train2017_filtrefgumdval_filtvlp.json'
----------------------------------
hello, I want to know how did you solve this problem ? I only find the "panoptic_train2017_filtrefgumdval_filtvlp.json" in [https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/v1.0/assets/readmes/DATASET.md](url) . I don't know where "panoptic_train2017_filtrefgumdval.json" is?
