### ISSUE TITLE
ModuleNotFoundError: No module named 'caption_pycocotools'

### ISSUE THREAD

**Issue by lizhiwen19900709** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#85]
![image](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/15767823/828f750c-85a5-4438-b6ab-a584f83d1bfb)

**Comment by MaureenZOU** [comment]
https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/v1.0/assets/readmes/INSTALL.md

**Comment by lizhiwen19900709** [comment]
@MaureenZOU All the operations in the installation document are done

**Comment by MaureenZOU** [comment]
Could you please check whether you have properly check the env variable?
`
export PATH=$PATH:/pth/to/xdecoder_data/coco_caption/jre1.8.0_321/bin
export PYTHONPATH=$PYTHONPATH:/pth/to/xdecoder_data/coco_caption
`

**Comment by lizhiwen19900709** [comment]
![image](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/15767823/2f6a63f6-c500-4436-a7be-68c8193315a4)

**Comment by lizhiwen19900709** [comment]
This problem is solved. I copied the folder into the project folder

**Comment by lizhiwen19900709** [comment]
![~(E7WJI932)%}EJR5} `D(X](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/15767823/3446a8e7-df84-4bb6-a307-1b49585d26f4)
I changed this place to the same file name as below, is that OK? Otherwise, the file will not be found, and the original declared file is not found in the tutorial

**Comment by lizhiwen19900709** [comment]
![1698754259219](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/15767823/50ecac9c-b155-49c8-a6f8-dc3f5baaf8d5)

**Comment by MaureenZOU** [comment]
If you properly solve the problem by copying the folder, that is potentially still caused by the bread export, try to see whether you have source ~/.bashrc properly. As copying folder may not be a clean solution : )

**Comment by lizhiwen19900709** [comment]
source ~/.bashrc did not work

**Comment by MaureenZOU** [comment]
The changing file is okay, but it may cause some information leakage. Thanks for letting me know this, I will upload the file ASAP (will try today).

**Comment by MaureenZOU** [comment]
which file do you add the export?

**Comment by lizhiwen19900709** [comment]
![image](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/15767823/a6d56f60-7467-4c26-9852-09b066d737dd)
Couldn't find the file marked in the comments section, so changed it to look like this

**Comment by MaureenZOU** [comment]
wait, the filtrefgumdval_filtvlp is correct.

**Comment by lizhiwen19900709** [comment]
Is there an error in the source code?

**Comment by MaureenZOU** [comment]
Nope, I think it is correct, and the way you comment is also correct
