### ISSUE TITLE
Training with Alternative Datasets

### ISSUE THREAD

**Issue by theodore-zhao** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#87]
I have been struggling with training with alternative dataset. Since my dataset is in the RefCOCO format, I wanted to test by training focall_unicl_lang_v1.yaml with refcocog_val_umd. I specified the dataset mapper to be the refcoco one, but still didn't work. As this can be a big question, I would appreciate if you could highlight a few critical steps on how to make training on datasets like RefCOCO work. Thank you!

**Comment by simranbajaj06** [comment]
@theodore-zhao 
what are the steps , you follow to train SEEM on your custom dataset
