### ISSUE TITLE
How to address the issue of objects mentioned in the prompt not appearing in the target image?

### ISSUE THREAD

**Issue by Ian990466** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#89]
Here's an example: I have a example image with a dog in it, but in my target image, there is no dog; it's just a grassy field. In this scenario, how can I ensure that the segmentation result neither produces an "other" label nor attempts segmentation?

**Comment by MaureenZOU** [comment]
It actually doesn't handle negative tokens now. Feel free to explore on that direction : )

**Comment by Dragobloody** [comment]
@Ian990466 did you manage to find a solution to your scenario? I'm struggling to find a solution to the same example you mentioned, when your prompt an object from a "prompting image" (e.g. a dog) that is not present in the target image (e.g. a grassy field).

**Comment by Ian990466** [comment]
@Dragobloody No, in fact, I think this type of problem may not be solvable with a single model. I believe such issues might require the integration of an object detection model to address the scenario.
