### ISSUE TITLE
SEEM in remote sensing images segmantation task.

### ISSUE THREAD

**Issue by Aki-Tomoya** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#90]
Thank you very much for your work! But I still find that there are still several problems. When segmenting remote sensing images, the results of the model used in your demo presentation perform very well. However, when I use several of the pre-trained models you posted (SEEM/X-Decoder), I find that the segmentation results are nowhere near as good, if not extremely bad, as your demo program. Do you have any idea what is going on here? Or can you open source the model (using Davit-d3 as backbone) that was used as demo demo?I choose the [panoramic] task when I use the app.py.

**Comment by Aki-Tomoya** [comment]
Also. I noticed that except for your demo model in huggingface (Davit-d3 as backbone), the other models don't have clear data boundaries (e.g., the "splash" problem mentioned in other issues), is this related to the fact that the other models are not trained on the SBD dataset?  (Noting that only Davit-d3 has SBD metrics in your checkpoint)

**Comment by Aki-Tomoya** [comment]
When I use the demo demo on huggingface for image segmentation, I get great results：
![下载](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/54172123/504734ba-3043-4fe0-a3ef-90a5177e0ad9)
But when I use the published pre-trained model for segmentation, I get poor results：
![out](https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/assets/54172123/167d8850-c93d-4adb-9fc5-600a798cb4cd)
Do you know what the problem is? What can I do to reproduce the results of the demo?

**Comment by MaureenZOU** [comment]
I see, thanks so much for your feedback, I could not release model checkpoint other than focalt, and focall, I sincerely apologize for the sub-optimal results.

**Comment by antopost** [comment]
Hi @MaureenZOU 
May I ask why you can't release the model weights used in the online demo?

**Comment by EricZavier** [comment]
may I ask if you obtained this result through training on your own annotated remote sensing dataset?

**Comment by Aki-Tomoya** [comment]
No. I chose other pre-training models to get my work done. :<

**Comment by Aki-Tomoya** [comment]
> may I ask if you obtained this result through training on your own annotated remote sensing dataset?
No. I chose other pre-training models to get my work done. :<

**Comment by Aki-Tomoya** [comment]
> may I ask if you obtained this result through training on your own annotated remote sensing dataset?

None. I chose other pre-training models to get my work done :<.
