### ISSUE TITLE
Can it be trained or fine-tuned on custom datasets?

### ISSUE THREAD

**Issue by SiChuChu** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#92]

**Comment by jwyang** [comment]
yes, it can but you may need to build a customized dataset mapper and data register in this folder: https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/tree/v1.0/datasets

**Comment by simranbajaj06** [comment]
how to build customized dataset mapper and data register @jwyang 
what are the steps to follow ?
I have to fine-tune SEEM on my custom dataset and i want bbox and segm both as a result, there are multiple files present in mapper folder which one to refer, what are the differences between them?
