### ISSUE TITLE
both visual and textual prompts demo?

### ISSUE THREAD

**Issue by zgyh001** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#94]
After training, our model becomes familiar with all prompt types and supports a variety of compositions, such as no prompts, one prompt type, or both visual and textual prompts using the same model and weights.

the demo code is only use one prompt type? How can i test both visual and textual prompts?

**Comment by MaureenZOU** [comment]
The demo is including all types of prompt.

**Comment by zgyh001** [comment]
Thanks for your reply.

In /demo/seem/tasks/interactive.py,  function of interactive_infer_image(), 'Stroke' 'Example' 'Text' and 'Audio' one time infering only use one of them, not one time infering use two or more selected? Everyone in tasks will output one "pred_masks_pos", but not all tasks feature merged as one "pred_masks_pos"?
