### ISSUE TITLE
Extract feature？

### ISSUE THREAD

**Issue by xwcUP** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#95]
Can the model extract features, and if so, how to extract image features？  Hope to get your reply，thanks a million.

**Comment by MaureenZOU** [comment]
Please refer to here: https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/7b2e76dbb17d0b7831c6813a921fe2bc8de22926/modeling/architectures/seem_model_v1.py#L453 for feature extraction.

**Comment by xwcUP** [comment]
Thank you for your reply, and if I want to extract features from a medical image, how do I need to change the code, or how can I change the data to apply my data?
