### ISSUE TITLE
medical images

### ISSUE THREAD

**Issue by xwcUP** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#96]
Thank you for your creation, I would like to ask a question, can medical images (like segmentation tumors) be trained with your model segmentation

**Comment by jwyang** [comment]
yes, it should work, we had tried it internally.

**Comment by xwcUP** [comment]
Thank you for your reply，can I segment it directly in the demo? Or do you want to import the dataset yourself and retrain it?
