### ISSUE TITLE
RefCOCOg Results

### ISSUE THREAD

**Issue by zifuwanggg** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#97]
I'm wondering why the released checkpoints have much lower results on RefCOCOg (~62-63% cIoU), as opposed the numbers reported in the paper (~64-65% cIoU)?

**Comment by MaureenZOU** [comment]
Because the released checkpoint is trained with focall, while the paper reports davit-d5 number that we are not allowed to open-source. Thanks!
