### ISSUE TITLE
CUDA version mismatch between X-Decoder and Detectron2

### ISSUE THREAD

**Issue by Trimble-cfouque** [UX-Decoder/Segment-Everything-Everywhere-All-At-Once#99]
Hello

I followed the install.md on a freshly made python env (3.8.18) 
The basic requirement file went fine but when installing detectron2 package in the requirement_custom i got an error about CUDA version mismatch : 

RuntimeError:
      The detected CUDA version (11.7) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.

Is my python version not adequate ? I couldn't find any guideline on which version i should use to run the code
How may I fix this error ?

**Comment by Trimble-cfouque** [comment]
Ok i found it, so detectron2 relies on the installed CUDA version on the machine, and it has to match the 12.1 that is brought with pytorch. So i need to upgrade my installed CUDA to 12.1

**Comment by mudasar10147** [comment]
I am trying to run it locally on my system. I am facing an issue with the installation of the requirements file. In one requirements file, there are all required packages and in the second one there are some Github repos(Detectorn, Whisper, einops), which need to be installed on the environment. But Despite of all my efforts i am unable to do it, do you have any idea about that?
